train_data: /apdcephfs/share_1316500/donchaoyang/code2/data/additional_urban_sed/h5/train_urban.h5
cv_data: /apdcephfs/share_1316500/donchaoyang/code2/data/additional_urban_sed/h5/validate_urban.h5
test_data: /apdcephfs/share_1316500/donchaoyang/code2/data/additional_urban_sed/h5/eval_urban.h5
spk_emb_file_path: /apdcephfs/share_1316500/donchaoyang/code2/data/additional_urban_sed/spk_embed.128.txt
batch_size: 128
num_workers: 8
mask_and_replace: 0.35
data_args:
    mode: stratified # Stratified split to train and cv
optimizer: AdamW
label: /apdcephfs/share_1316500/donchaoyang/code2/data/additional_urban_sed/filelist/strong_urban_eval_neg_psd.tsv
metadata: /apdcephfs/share_1316500/donchaoyang/code2/data/additional_urban_sed/filelist/mata_urban_eval.tsv
optimizer_args:
    lr: 0.001
epochs: 100 
model: S_student
model_args:
    temppool: linear
outputpath: /apdcephfs/share_1316500/donchaoyang/code2/experiments_weakly/Urban_S_student_035n2
transforms: [freqmask, timemask, shift]
shuffle: False
sampler: MinimumOccupancySampler
loss: BCELoss
save: one
early_stop: 7
scheduler_args:
    patience: 3
    factor: 0.1
scale: 4
postprocessing: median
thres: 0.5
dtc_threshold: 0.7
gtc_threshold: 0.7
cttc_threshold: 0.3
alpha_ct: 0.0
alpha_st: 1
max_efpr: 100
experiment_description: In this experiment,we mainly test S_student