# train_data: /apdcephfs/share_1316500/donchaoyang/code2/data/feature_wtsd/train.h5
# cv_data: /apdcephfs/share_1316500/donchaoyang/code2/data/feature_wtsd/validate.h5
# test_data: /apdcephfs/share_1316500/donchaoyang/code2/data/feature_wtsd/eval.h5
train_data: /apdcephfs/share_1316500/donchaoyang/code2/data/feature_tsd/train_add_neg_final.h5
cv_data: /apdcephfs/share_1316500/donchaoyang/code2/data/feature_tsd/validate_add_neg_final.h5
test_data: /apdcephfs/share_1316500/donchaoyang/code2/data/feature_tsd/eval_add_neg_final.h5
# train_data: /apdcephfs/share_1316500/donchaoyang/code2/data/additional_class_choose/strong_feature/train_additional.h5
# cv_data: /apdcephfs/share_1316500/donchaoyang/code2/data/additional_class_choose/strong_feature/eval_additional.h5
# test_data: /apdcephfs/share_1316500/donchaoyang/code2/data/additional_class_choose/strong_feature/eval_additional.h5
spk_emb_file_path: /apdcephfs/share_1316500/donchaoyang/code2/data/embeddings/spk_embed.128.txt
# 1 reverse, 2 no_reverse
#stage1_path: /apdcephfs/share_1316500/donchaoyang/code2/experiments_weakly/Urban_Stage1/Stage1/2021-12-07_10-22-12_8d3a6c50570411ec885f91a4b3a6487e/run_model_21_loss=-0.5122.pt
stage1_path: /apdcephfs/share_1316500/donchaoyang/code2/exp_weakly/AudioSet_Stage1_bce/Stage1/2022-02-25_15-20-02_66db2ebe960b11ecbc01c9acd29d99a9/run_model_16_loss=-0.4466.pt
batch_size: 128
num_workers: 8
data_args:
    mode: stratified # Stratified split to train and cv
optimizer: AdamW
# label: /apdcephfs/share_1316500/donchaoyang/code2/data/weakly_data/strong_eval_for_weakly.tsv
label: /apdcephfs/share_1316500/donchaoyang/code2/data/choose_class/strong_and_weakly_eval_psds.tsv
#label: /apdcephfs/share_1316500/donchaoyang/code2/data/additional_class_choose/filelist/strong_additional_eval_neg_psd.tsv
metadata: /apdcephfs/share_1316500/donchaoyang/code2/data/choose_class/mata_eval_choose.tsv
optimizer_args:
    lr: 0.0001
epochs: 100 
model: Stage2
model_args:
    temppool: linear
outputpath: /apdcephfs/share_1316500/donchaoyang/code2/exp_weakly/AudioSet_Stage2_bce
transforms: [freqmask, timemask, shift]
shuffle: False
sampler: MinimumOccupancySampler
loss: BCELoss
save: one
early_stop: 7
scheduler_args:
    patience: 3
    factor: 0.1
scale: 4
postprocessing: median
thres: 0.5
dtc_threshold: 0.7
gtc_threshold: 0.7
cttc_threshold: 0.3
alpha_ct: 0.0
alpha_st: 1
max_efpr: 100
experiment_description: In this experiment,we mainly test add weakly dataset in dataset on stage2, and the stage1 is based on no_reverse